blog/urls.py
from django.conf.urls import url, include
from .views import index, category, article_detail, archive, author_article, tag_article, awesome_click

app_name = 'blog'
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^category/(?P<id>\d+)/$', category, name='category'),
    url(r'^article/(?P<id>\d+)/$', article_detail, name='article'),
    url(r'^archive/(?P<year>\d{4})/(?P<month>\d{1,2})/$', archive, name='archive'),
    url(r'^author_article/(?P<id>\d+)/$', author_article, name='author_article'),
    url(r'^tag_article/(?P<id>\d+)/$', tag_article, name='tag_article'),
    url(r'^awesome_click/$', awesome_click, name='awesome_click'),
]

comments/urls.py
from django.conf.urls import url
from .views import post_comment

app_name = 'comments'
urlpatterns = [
    url(r'^article/(?P<id>\d+)/$', post_comment, name='comment'),
]

firstblog_pro/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from blog.views import index
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^comment/', include('comments.urls')),
    url(r'', include('blog.urls')),
]

if settings.DEBUG :
    urlpatterns += [
        url(r'^media/(?P<path>.*)', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

users/urls.py
from django.conf.urls import url
from .views import register

app_name = 'user'
urlpatterns = [
    url(r'^register/$', register, name='register'),
]

blog/models.py
from django.db import models
from django.utils.html import strip_tags
from markdownx.models import MarkdownxField

# Create your models here.


# 定义文章分类，有一个排序字段，用于自定义文章在导航条上的显示顺序
# 一篇文章对应一个分类，一个分类可以有多篇文章
class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name='分类名称')
    index = models.IntegerField(default=50, verbose_name='分类排序')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ['index', 'name']


# 定义标签，一个文章可以有多个标签，一个标签也可以对应多篇文章
class Tag(models.Model):
    name = models.CharField(max_length=30, verbose_name='标签名称')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name


# 定义文章，文章所属作者与usersAPP中的User关联
class Article(models.Model):
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=100, blank=True, verbose_name='文章描述')
    # content = models.TextField(verbose_name='文章内容')
    content = MarkdownxField(verbose_name='文章内容')
    click_count = models.IntegerField(default=0, verbose_name='点击次数')
    awesome_count = models.IntegerField(default=0, verbose_name='点赞数')
    recommend_index = models.IntegerField(default=100, verbose_name='推荐顺序')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    author = models.ForeignKey('users.User', verbose_name='作者')
    category = models.ForeignKey(Category, blank=True, verbose_name='所属分类')
    tag = models.ManyToManyField(Tag, verbose_name='所属标签')

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-date_publish']

    def __str__(self):
        return self.title

    def save(self):
        if not self.desc:
            self.desc = strip_tags(self.content)[:54]
        super(Article, self).save()


# 友情链接
class Link(models.Model):
    title = models.CharField(max_length=50, verbose_name="链接标题")
    desc = models.CharField(max_length=200, verbose_name="链接描述")
    url = models.URLField(verbose_name="链接地址")
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name="发布时间")
    index = models.IntegerField(default=999, verbose_name="排序（从小到大）")

    class Meta:
        verbose_name = "友情链接"
        verbose_name_plural = verbose_name
        ordering = ['index', 'id']

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from .models import Article, Category, Tag
from users.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import markdown
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from comments.forms import CommentForm
# Create your views here.


# 定义主页的视图函数，主页上的大部分内容都通过我们自定义的模板标签进行了渲染
# 还剩下--左边：文章列表和分页需要我们在这里处理
def index(request):
    article_list = Article.objects.all()
    article_list = page_article(request, article_list)
    context = {
        'article_list': article_list,
    }
    return render(request,'blog/index.html', context=context)


# 定义点击导航栏中分类时的视图函数
def category(request, id):
    article_list = Article.objects.filter(category_id=id)
    article_list = page_article(request, article_list)
    category_result = Category.objects.get(id=id)
    context = {
        'article_list': article_list,
        'category_result': category_result,
    }
    return render(request, 'blog/result-list.html', context=context)


# 每篇文章详情视图函数
def article_detail(request, id):
    article = Article.objects.get(id=id)
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
       TocExtension(slugify=slugify),
    ])
    article.content = md.convert(article.content)
    comment_list = article.comment_set.all()
    form = CommentForm()
    context = {
        'article': article,
        'comment_list': comment_list,
        'toc':md.toc,
        'form': form,
    }
    return render(request, 'blog/article.html', context=context)


# 右侧按时间归档的视图函数
def archive(request, year, month):
    article_list = Article.objects.filter(date_publish__year=year, date_publish__month=month)
    article_list = page_article(request, article_list)
    archive_time = year + "年" + month + "月"
    context = {
        'article_list': article_list,
        'archive_time': archive_time,
    }
    return render(request, 'blog/result-list.html', context=context)


# 按照作者名来获取文章，作者与文章之间是一对多的关系
def author_article(request, id):
    user = User.objects.get(id=id)
    article_list = user.article_set.all()
    article_list = page_article(request, article_list)
    context = {
        'article_list': article_list,
        'user': user,
    }
    return render(request, 'blog/result-list.html', context=context)


# 按照标签来获取文章，标签与文章之间是多对多的关系
def tag_article(request, id):
    tag = Tag.objects.get(id=id)
    # tag = get_object_or_404(Tag, id=id)
    article_list = tag.article_set.all()
    article_list = page_article(request, article_list)
    context = {
        'article_list': article_list,
        'tag': tag,
    }
    return render(request, 'blog/result-list.html', context=context)


# 始终牢记这个函数得到的只是某一页文章列表的object
# 这个值传递到templates中去之后，可以调用article.paginator.page_range这样的值
# 这里控制一页显示多少篇文章
def page_article(request, article_list):
    paginator = Paginator(article_list, 5)
    page = request.GET.get('page')
    try:
        article = paginator.page(page)
    except PageNotAnInteger:
        article = paginator.page(1)
    except EmptyPage:
        article = paginator.page(paginator.num_pages)
    return article


def awesome_click(request):
    if request.method == 'GET':
        print(request.GET)
        arti_id = request.GET['article_id']
        print(arti_id)
    awesome = 0
    if arti_id:
        article = Article.objects.get(id=int(arti_id))
        if article:
            awesome = article.awesome_count + 1
            article.awesome_count = awesome
            article.save()
            awesome = '<span class="glyphicon glyphicon-thumbs-up">%s</span>' % (awesome,)

    return HttpResponse(awesome)

templates/blog/article.html
{% extends 'blog/base.html' %}
{% load myfilter %}

{% block title %}
<title>文章详情页</title>
{% endblock %}

{% block main %}
<div class="container">
    <div class="row row-offcanvas row-offcanvas-right">
        <!--左边自动生成目录start-->
 		<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
            <div class="affix">
                <p>文章目录</p>
               {{ toc | safe }}
            </div>
        </div>
        <!--左边end-->

        <!--右侧栏文章详情及评论start-->
        <div class="col-xs-12 col-sm-9">
            <div class="row">
                <div class="col-xs-6 col-lg-11">
                    <!--文章标题-->
                  <h2>{{ article.title }}</h2>

                    <!--文章脚注-->
                  <p >
                      <a href="{% url 'blog:author_article' article.author_id %}" style="padding-right: 10px; color: #2aabd2"><span class="glyphicon glyphicon-user">{{ article.author }}</span></a>
                      <a href="{% url 'blog:category' article.category_id %}" style="padding-right: 10px; color: #2aabd2"><span class="glyphicon glyphicon-book">{{ article.category }}</span></a>
                      <a style="padding-right: 10px; color: #2aabd2;"><span class="glyphicon glyphicon-time">{{ article.date_publish }}</span></a>
                      <span style="float: right">
                        <a style="padding-right: 10px; color: black"><span class="glyphicon glyphicon-eye-open">({{ article.click_count }})</span></a>
                          <a href="{% url 'blog:awesome_click' %}" style="padding-right: 10px; color: red" id="awesome_count"><span class="glyphicon glyphicon-thumbs-up">({{ article.awesome_count }})</span></a>
                          <button type="button" id="awesome" arti_id="{{ article.id }}">点我</button>
                      </span>
                  </p>

                    <!--文章内容-->
                    <p style="margin-top: 40px;font-size: medium;line-height: 1.8em;">
                        {{ article.content | safe }}
                    </p>

                    <hr>
                    <!--文章评论-->
                    <div style="font-size: small">
                        {% for comment in comment_list %}
                        <div class="media" >
                          <div class="media-left">
                            <a href="#">
                              <img class="media-object" src="{{ comment.username.user_img.url }}" alt="...">
                            </a>
                          </div>
                          <div class="media-body" style="background-color: #e8e8e8">
                            <h4 class="media-heading" style="color: blue">{{ comment.username }}</h4>
                            <p style="font-size: 13px;">
                                {{ comment.content }}
                            </p>
                              <p style="text-align: right">{{ comment.date_publish }}</p>
                          </div>
                        </div>
                        {% endfor %}
                    </div>

                    <hr>
                    <!--评论表单-->
                    <div>
                        {% if user.is_authenticated %}
                            <form class="form-horizontal" action="{% url 'comments:comment' article.id %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                <label for="textarea1" class="col-sm-2 control-label">评论内容</label>
                                    <div class="col-sm-10">
                                        {% for field in form %}
                                            {{ field | addclass:'form-control' }}
                                        {% endfor %}
{#                                      <textarea id="textarea1" class="form-control" rows="5"></textarea>#}
                                    </div>
                                </div>
                              <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                  <button type="submit" class="btn btn-default">提交</button>
                                </div>
                              </div>
                        </form>
                        {% else %}
                            <h5>
                                只有登录用户才能评论哦 &nbsp <a href="{% url 'user:register' %}">注册</a>  <a href="{% url 'login' %}?next={{ request.path }}">登录</a>
                            </h5>
                            {{ form }}
                        {% endif %}
                    </div>

                </div><!--/.col-xs-6.col-lg-4-->
            </div>
        </div>
        <!--右侧栏end-->


    </div>
</div>
{% endblock %}

templates/blog/base-index.html
{% extends 'blog/base.html' %}
{% load my_blog_tags %}
{% load staticfiles %}

{#这个文件继承自base.html，但是还有其他的文件是继承于这个文件，用到了多重继承#}

{% block main %}
<div class="container">
    <div class="row row-offcanvas row-offcanvas-right">

        <!--左边start-->
        <div class="col-xs-12 col-sm-7 col-sm-offset-1">

            {% block leftad %}
            {% endblock %}


            <h3 style="margin-top: 50px;">
                <span>
                    {% block article_type %}
                    {% endblock %}
                </span>
                文章列表：
            </h3>
            <hr/>
            <!--文章列表start-->
            <div class="row">
                {% for article in article_list %}
                <div class="col-xs-6 col-lg-12">
                  <a href="{% url 'blog:article' article.id %}" target="_blank"><h4 style="font-weight: bold; color: black">{{ article.title }}</h4></a>
                  <p>{{ article.desc }}</p>
                  <p>
                      <a href="{% url 'blog:author_article' article.author_id %}" style="padding-right: 10px; color: #2aabd2"><span class="glyphicon glyphicon-user">{{ article.author }}</span></a>
                      <a href="{% url 'blog:category' article.category_id %}" style="padding-right: 10px; color: #2aabd2"><span class="glyphicon glyphicon-book">{{ article.category }}</span></a>
                      <a style="padding-right: 10px; color: #2aabd2;"><span class="glyphicon glyphicon-time">{{ article.date_publish }}</span></a>
                      <span style="float: right">
                        <a style="padding-right: 10px; color: black"><span class="glyphicon glyphicon-eye-open">({{ article.click_count }})</span></a>
                          <a href="#" style="padding-right: 10px; color: red"><span class="glyphicon glyphicon-thumbs-up">({{ article.awesome_count }})</span></a>
                      </span>
                  </p>
                </div><!--/.col-xs-6.col-lg-4-->
                {% endfor %}
            </div>
            <!--文章列表end-->

            <!--分页start-->
            <div class="row pull-right">
            <nav aria-label="Page navigation" >
              <ul class="pagination" style="float: left">
                  {% if article_list.has_previous %}
                    <li>
                      <a href="?page={{ article_list.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                      </a>
                    </li>
                  {% endif %}
                  {% for pgnum in article_list.paginator.page_range %}
                      {% if pgnum == article_list.number %}
                        <li class="active"><a href="?page={{ pgnum }}">{{ pgnum }}</a></li>
                      {% else %}
                        <li><a href="?page={{ pgnum }}">{{ pgnum }}</a></li>
                      {% endif %}
                    {% endfor %}
                   {% if article_list.has_next %}
                      <li>
                          <a href="?page={{ article_list.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                          </a>
                      </li>
                  {% endif %}
              </ul>
            </nav>
            </div>
            <!--分页end-->

		</div>
        <!--左边end-->


        <!--右侧栏start-->
        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">

                    <!--文章排行start-->
                    <div class="list-group" style="margin-bottom: 50px;">
                        <h3>文章排行</h3>
                         <!-- 选项卡组件（菜单项nav-tabs）-->
                        <ul id="myTab" class="nav nav-tabs nav-justified" role="tablist">
                          <li class="active small"><a href="#bulletin" role="tab" data-toggle="tab">博主推荐</a></li>
                          <li class="small"><a href="#rule" role="tab" data-toggle="tab">点赞最多</a></li>
                          <li class="small"><a href="#forum" role="tab" data-toggle="tab">热议文章</a></li>
                        </ul>
                        <!-- 选项卡面板 -->
                        <div id="myTabContent" class="tab-content">
                          <div class="tab-pane active" id="bulletin">
                              <ol class="list-group">
                                  {% get_recommend as article_list %}
                                  {% for article in article_list %}
                                  <a href="{% url 'blog:article' article.id %}"><li class="list-group-item small text-nowrap">{{ article.title }}</li></a>
                                  {% endfor %}
                              </ol>
                          </div>
                          <div class="tab-pane" id="rule">
                              <ol class="list-group">
                                  {% get_awesome_count as article_list %}
                                  {% for article in article_list %}
                                      <a href="{% url 'blog:article' article.id %}"><li class="list-group-item small">{{ article.title }}</li></a>
                                  {% endfor %}
                              </ol>
                          </div>
                          <div class="tab-pane" id="forum">
                              <ol class="list-group">
                                  {% get_comment_count as article_list %}
                                  {% for article in article_list %}
                                      <a href="{% url 'blog:article' article.id %}"><li class="list-group-item small">{{ article.title }}</li></a>
                                  {% endfor %}
                              </ol>
                          </div>
                        </div>
                    </div>
                    <!--文章排行end-->

                    <!--文章归档start-->
                    <div class="list-group" style="margin-bottom: 50px;">
                         <h3>文章归档</h3>
                        {% get_archives as date_list %}
                        {% for date in date_list %}
                        <a href="{% url 'blog:archive' date.year date.month %}" class="list-group-item">
                            {{ date.year }}年{{ date.month }}月文章
                            <span class="badge">
                                {% get_archive_count %}
                            </span>
                        </a>
                        {% endfor %}
                    </div>
                    <!--文章归档end-->

                    <!--标签云start-->
                    <div class="list-group" style="margin-bottom: 50px;">
                        <h3>标签云</h3>
                        <h5 style="line-height: 2.0em;">
                            {% get_tags as tag_list %}
                            {% for tag in tag_list %}
                                <a href="{% url 'blog:tag_article' tag.id %}" style="text-decoration: none"><span class="label">{{ tag.name }}</span></a>
                            {% endfor %}
        {#                <a href="#" style="text-decoration: none"><span class="label label-primary">主要标签</span></a>#}
        {#                <span class="label label-success">成功标签</span>#}
        {#                <span class="label label-info">信息标签</span>#}
        {#                <span class="label label-warning">警告标签</span>#}
        {#                <span class="label label-danger">危险标签</span>#}
                        </h5>
                    </div>
                    <!--标签云end-->
        
                    <!--标签云随机颜色start-->
                    <script>
                        $(function () {
                            $("h5 a span").each(function () {
                                $(this).addClass(getRandomcolor());
                            });
                        });
                        function getRandomcolor() {
                            var c = Math.floor(Math.random()*5)
                            var color = ['label-default','label-primary','label-success','label-info','label-warning','label-danger']
                            return color[c]
                        }
                    </script>
                    <!--标签云随机颜色end-->
        
                    <!--友情链接start-->
                    <div class="list-group" style="margin-bottom: 50px;">
                        <h3>友情链接</h3>
                        <h5 style="line-height: 2.0em;">
                            {% get_links as link_list %}
                            {% for link in link_list %}
                                <a href="{{ link.url }}" style="text-decoration: none"><span class="label">{{ link.title }}</span></a>
                            {% endfor %}
                        </h5>
                    </div>
                    <!--友情链接end-->

        </div>
        <!--右侧栏end-->
    </div>
</div>
{% endblock %}

templates/blog/base.html
{% load staticfiles %}
{% load my_blog_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href={% static 'blog/css/bootstrap.min.css' %}>
    <link rel="stylesheet" href={% static 'blog/css/bootstrap-theme.min.css' %}>
	<link rel="stylesheet" href={% static 'blog/css/offcanvas.css' %}>
	<link rel="stylesheet" href={% static 'blog/css/github.css' %}>
    <script rel="stylesheet" src={% static 'blog/js/jquery.min.js' %}></script>
    <script type="text/javascript" src={% static 'blog/js/bootstrap.min.js' %}></script>
    <script type="text/javascript" src={% static 'blog/js/blog-ajax.js' %}></script>
    <style>
        span.highlighted {
            color: red;
        }
    </style>
</head>
<body>
{% include 'blog/nav.html' %}

{% block main %}
{% endblock %}

{% include 'blog/footer.html' %}
</body>
</html>

templates/blog/footer.html
<hr>
<footer>
    <div class="container">
    <p class="text-muted text-center">&copy; Copyright 2017</p>
    </div>
</footer>

templates/blog/index.html
{% extends 'blog/base-index.html' %}
{% load my_blog_tags %}
{% load staticfiles %}

{% block title %}
<title>Nokia的个人博客</title>
{% endblock %}

{% block leftad %}
<!--导航图片-->
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
              <!-- Indicators -->

              <ol class="carousel-indicators">
                {% get_ad as ad_list %}
                {% for ad in ad_list %}
                    {% if forloop.first %}
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    {% elif not forloop.first %}
                        <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}"></li>
                    {% endif %}
                {% endfor %}
              </ol>


              <!-- Wrapper for slides -->
              <div class="carousel-inner" role="listbox">
                    {% get_ad as ad_list %}
                    {% for ad in ad_list %}
                        {% if forloop.first  %}
                            <div class="item active">
                              <a href="{{ ad.url }}" target="_blank"><img src="{{ ad.img.url }}" alt="ad-img"></a>
                              <div class="carousel-caption">
                                <h3>{{ ad.title }}</h3>
                                <p>{{ ad.desc }}</p>
                              </div>
                            </div>
                        {% elif not forloop.first %}
                            <div class="item">
                              <a href="{{ ad.url }}" target="_blank"><img src="{{ ad.img.url }}" alt="..."></a>
                              <div class="carousel-caption">
                                <h3>{{ ad.title }}</h3>
                                <p>{{ ad.desc }}</p>
                              </div>
                            </div>
                        {% endif %}
                    {% endfor %}
              <!-- Controls -->
              <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
                </a>
            </div>
    </div>
<!--导航图片end-->
{% endblock %}


{% block article_type %}
    最新
{% endblock %}

templates/blog/nav.html
{% load my_blog_tags %}
<!--导航栏start-->
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Nokia</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
          {% get_categories as category_list %}
          {% for category in category_list %}
            <li><a href="{% url 'blog:category' category.id %}">{{ category.name }}</a></li>
          {% endfor %}
      </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="#"><span class="glyphicon glyphicon-user"></span> {{ user.username }}</a></li>
                <li><a href="{% url 'logout' %}?next={{ request.path }}"><span class="glyphicon glyphicon-log-in"></span> 注销</a></li>
            {% else %}
              <li><a href="{% url 'user:register' %}"><span class="glyphicon glyphicon-user"></span> 注册</a></li>
              <li><a href="{% url 'login' %}?next={{ request.path }}"><span class="glyphicon glyphicon-log-in"></span> 登录</a></li>
            {% endif %}
        </ul>
        <form class="navbar-form navbar-right" role="search" method="get" action="{% url 'haystack_search' %}">
            <div class="form-group">
                <input type="text" name="q" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">搜索</button>
        </form>
    </div><!-- /.nav-collapse -->
  </div><!-- /.container -->
</nav>
<!--导航栏end-->

templates/blog/result-list.html
{% extends 'blog/base-index.html' %}
{% load my_blog_tags %}
{% load staticfiles %}

{% block title %}
<title>{{ category_result.name }}文章列表</title>
{% endblock %}


{% block article_type %}
    {% if category_result %}
        {{ category_result.name }}
    {% elif archive_time %}
        {{ archive_time }}
     {% elif tag %}
        {{ tag.name }}标签
    {% elif user %}
        {{ user.username }}
    {% endif %}
{% endblock %}